config/routes.rb
Rails.application.routes.draw do
  resources :profiles do
    resources :ratings, only: [:create]
  end
  root to: 'profiles#index'
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:registrations]
  resources :pull_requests
  get 'repo_details/:username/:repo', to: 'profiles#repo_details', as: 'repo_details'
  get '/search', to: 'search#index'  # Point to the SearchController#index action
  post '/pull_requests', to: 'pull_requests#create', as: 'create_pull_request'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :ratings
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :profile

  validates :score, inclusion: { in: 1..5, message: "should be between 1 to 5" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:github]
  has_one :profile
  has_many :ratings

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        user_name: data['nickname'],
        email: data['email'],
        password: Devise.friendly_token[0,20],
        github_token: access_token.credentials.token # store the token
      )
    else
      user.update(github_token: access_token.credentials.token) # update the token if user already exists
    end

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found(exception)
    render json: { error: I18n.t('record_not_found', record: exception.model) }, status: :not_found
  end

  def search
    term = params[:term].downcase
    users = User.where('lower(name) LIKE ? OR lower(email) LIKE ?', "%#{term}%", "%#{term}%")
    profiles = Profile.where('lower(user_name) LIKE ? OR lower(location) LIKE ? OR phone_number LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
    suggestions = users.pluck(:name, :email) + profiles.pluck(:user_name, :location, :phone_number)
    suggestions.flatten!
    render json: suggestions
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i( show edit update destroy )
  before_action :authorize_user, only: %i( edit update destroy )
  before_action :authorize_github_user, only: %i( new show )

  def index
    @profiles = Profile.includes(:ratings).all.paginate(page: params[:page], per_page: 10)
    @average_ratings = @profiles.map do |profile|
      (profile.ratings.average(:score) || 0).to_f.round(2)
    end

    @ratings = {}
    @profiles.each do |profile|
      @ratings[profile.id] = profile.ratings.build
    end
  end

  def show
    repos = RepoService.fetch_all_repos(@profile.github_username, current_user)
    @repos = WillPaginate::Collection.create(params[:page] || 1, 10, repos.size) do |pager|
      pager.replace(repos[pager.offset, pager.per_page])
    end
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
    end
  end

  def repo_details
    @repo = RepoService.fetch_repo(params[:username], params[:repo], current_user)
    @pull_requests = PullRequestService.fetch_pull_requests(current_user, current_user.user_name, params[:repo]) if current_user.user_name == @repo['owner']['login']
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def authorize_github_user
    unless current_user.user_name.present?
      redirect_to profiles_url, alert: 'You are not authorized to perform this action. Make sure you are signed in using Github'
    end
  end

  def authorize_user
    unless @profile.user == current_user
      redirect_to profiles_url, alert: 'You are not authorized to perform this action. Make sure you are signed in using Github'
    end
  end

  def profile_params
    params.require(:profile).permit(:location, :phone_number, :image, :user_id, :github_username, skills: [])
  end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  def new
    @pull_request = PullRequest.new
    @repo = params['repo']
    @branches = PullRequestService.fetch_branches(current_user, current_user.user_name, @repo)
  end

  def create
    @pull_request = PullRequest.new(pull_request_params)
    if @pull_request.valid?
      success, response = PullRequestService.create(
        current_user,
        @pull_request.username,
        @pull_request.repo,
        @pull_request.title,
        @pull_request.head,
        @pull_request.base,
        @pull_request.body
      )

      if success
        set_branches_and_repo
        redirect_to repo_details_path(username:  current_user.user_name, repo: @repo), notice: "Pull request created successfully!"
      else
        set_branches_and_repo
        redirect_to new_pull_request_path(repo: @repo), alert: "Error creating pull request: #{response}"
      end
    else
      set_branches_and_repo
      redirect_to new_pull_request_path(repo: @repo)
    end
  end

  private

  def pull_request_params
    params.require(:pull_request).permit(:username, :repo, :title, :head, :base, :body)
  end

  def set_branches_and_repo
    @repo = @pull_request.repo
    @branches = PullRequestService.fetch_branches(current_user, current_user.user_name, @repo)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_profile
  before_action :authenticate_user!

  def create
    @rating = @profile.ratings.find_or_initialize_by(user: current_user)
    @rating.score = rating_params[:score]

    if @rating.save
      redirect_to profiles_path, notice: "Rating was successfully created."
    else
      redirect_to profiles_path, alert: @rating.errors.full_messages.to_sentence
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def rating_params
    params.require(:rating).permit(:score)
  end
end

app/controllers/search_controller.rb
# app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    term = params[:term].downcase
    profiles = Profile.where('lower(github_username) LIKE ? OR lower(location) LIKE ? OR phone_number LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
    suggestions = profiles.pluck(:github_username, :id).map { |github_username, id| "#{id} - #{github_username}" }
    render json: suggestions
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_link_path(user)
    if user.profile
      profile_path(user.profile)
    else
      new_profile_path
    end
  end
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
end

app/views/home/welcome.html.erb
<h1>Here<h1>
<button class="btn btn-primary">click</button>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" >GitInsight</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <% if current_user %>
          <%= link_to "Profile", profile_link_path(current_user), class: "nav-link" %>
        <% end %>
      </li>
    </ul>
    <% if current_user && current_user.user_name.nil? %><p class="pt-3 pr-2 text-danger">You are not a Github User</p><% end %>
    <form class="form-inline my-2 my-lg-0 position-relative">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="search-input">
      <div id="search-results" class="position-absolute"></div>
    </form>

    <% if user_signed_in? %>
      <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: 'mx-3 btn btn-primary'%>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitInsight</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%if current_user%><%= render 'layouts/navbar' %><% end %>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <div class="px-4 mx-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, class: "form") do |form| %>
  <% if profile.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="px-4 mx-4">
    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :phone_number %>
      <%= form.text_field :phone_number, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :user_id, style: "display: none;" %>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>


    <div class="form-group">
      <%= form.label :github_username %>
      <%= form.text_field :github_username, class: "form-control", value: current_user.user_name%>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: "form-control-file" %>
    </div>

    <div class="form-group">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>" class="container">
  <div class="row border-bottom pb-4 mb-4">
    <div class="col-md-10">
      <p>
        <strong>Location:</strong>
        <%= profile.location %>
      </p>

      <p>
        <strong>Phone number:</strong>
        <%= profile.phone_number %>
      </p>

      <p>
        <strong>User:</strong>
        <%= profile.user_id %>
      </p>

      <p>
        <strong>Github username:</strong>
        <%= profile.github_username %>
      </p>

      <p>
        <strong>Skills:</strong>
        <%= profile.skills.join(', ') %>
      </p>
    </div>

    <div class="col-md-2">
      <% if profile.image.attached? %>
        <%= image_tag profile.image, class: "img-thumbnail rounded " %>
      <% else %>
        <p>No image uploaded.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="my-4">Profiles</h1>
      <div id="profiles">
        <% @profiles.each_with_index do |profile, index| %>
          <div class="card mb-4 shadow-lg p-3 mb-5 bg-body rounded">
            <div class="card-body">
              <!-- You can replace this with the actual image tag -->
              <%= render profile %>

              <% if profile.user != current_user %>
                <%= form_with model: [profile, @ratings[profile.id]], local: true, class: 'mt-3' do |form| %>
                  <div class="form-group">
                    <%= form.label :score, 'Rate this profile:' %>
                    <%= form.number_field :score, in: 1..5, step: 1, class: 'form-control' %>
                  </div>
                  <%= form.submit "Rate", class: 'btn btn-primary mt-3' %>
                <% end %>
              <% end %>

              <div class="d-flex justify-content-between align-items-center mt-3">
                <div>
                  <% if current_user.user_name %>
                    <%= link_to "Show this profile", profile, class: 'btn btn-info' %>
                  <% else %>
                    <%= button_to "Sign In with Github to View Profile", destroy_user_session_path, method: :delete, class: ''%>
                  <% end %>
                </div>
                <div>
                  <span class="badge bg-warning p-2">
                    Average Rating: <%= @average_ratings[index].round(2) %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= will_paginate @profiles, class: 'pagination', previous_label: '&laquo; Prev', next_label: 'Next &raquo;' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/repo_details.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-12 shadow-lg p-3 mb-3 bg-body rounded">
      <div class="mb-4">
        <h1><a href="<%= @repo['html_url'] %>"><%= @repo['full_name'] %></a></h1>
        <p><%= @repo['description'] %></p>
      </div>
      <hr>
      <h3>Repository Details:</h3>
      <ul class="list-group">
        <li class="list-group-item"><strong>Owner:</strong> <%= @repo['owner']['login'] %></li>
        <li class="list-group-item"><strong>Created At:</strong> <%= @repo['created_at'] %></li>
        <li class="list-group-item"><strong>Updated At:</strong> <%= @repo['updated_at'] %></li>
        <li class="list-group-item"><strong>Language:</strong> <%= @repo['language'] %></li>
      </ul>
      <% if current_user.user_name == @repo['owner']['login']%>
        <div class="mt-4">
          <li class="list-group-item">
              <%= link_to "Create Pull Request", new_pull_request_path(repo: @repo['name']), class: "btn btn-primary" %>
          </li>
        </div>
      <% end %>
    </div>
    <% if current_user.user_name == @repo['owner']['login']%>
      <div class="col-md-12 shadow-lg p-3 bg-body rounded">
        <h2>Pull Requests</h2>
        <div>
          <% if @pull_requests.any? %>
            <% @pull_requests.each do |pr| %>
              <div class="shadow-sm p-3 bg-body rounded-lg">
                <h3><%= pr['title'] %></h3>
                <div class="d-flex justify-content-between">
                  <p>Submitted by: <%= pr['user']['login'] %></p>
                  <p class="bg-primary p-1 rounded-sm">Status: <%= pr['state'] %></p>
                </div>
                <div class="d-flex justify-content-between">
                  <p>Created at: <%= Time.zone.parse(pr['created_at']).strftime("%B %d, %Y") %></p>
                  <p>Last updated at: <%= Time.zone.parse(pr['updated_at']).strftime("%B %d, %Y") %></p>
                </div>
                <a href="<%= pr['html_url'] %>">View on GitHub</a>
              </div>
            <% end %>
        </div>
        <% else %>
          <p>No Pull Requests</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="shadow p-3 mb-5 bg-body rounded container p-4">
  <%= render @profile %>
</div>

<div class="container shadow p-3 mb-5 bg-body rounded p-4">
  <h3>Repositories:</h3>
  <ul class="list-group">
    <% @repos.each do |repo| %>
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <%= link_to repo['full_name'], repo_details_path(username: @profile.github_username, repo: repo['name']) %>
          <span class="badge bg-primary"><%= repo['language'] %></span>
        </div>
        <p><%= repo['description'] || 'No description available' %></p>
      </li>
    <% end %>
  </ul>
  <% if @profile.user == current_user %>
    <div class="container mt-3 d-flex justify-content-end">
      <%= link_to "Edit this profile", edit_profile_path(@profile), class: "btn btn-primary m-2" %>
      <%= button_to "Destroy this profile", @profile, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger m-2" %>
    </div>
  <% end %>
  <div class="float-right p-4">
    <%= will_paginate @repos, class: '', previous_label: '&laquo; Prev', next_label: 'Next &raquo;' %>
  </div>
</div>

app/views/pull_requests/new.html.erb
<%= form_with(model: @pull_request, url: create_pull_request_path, method: :post, local: true, class: "needs-validation") do |form| %>
  <div class="form-group" >
    <%= form.text_field :username, class: "form-control", value: current_user.user_name, required: true, style: "display: none;" %>
    <div class="invalid-feedback">Please enter your username.</div>
  </div>

  <div class="form-group">
    <%= form.text_field :repo, class: "form-control", value: @repo, required: true, style: "display: none;" %>
  </div>

  <div class="form-group">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
    <div class="invalid-feedback">Please enter the title.</div>
  </div>

  <div class="form-group">
    <%= form.label :head, class: "form-label" %>
    <%= form.select :head, @branches.map { |branch| [branch['name'], branch['name']] }, { prompt: 'Select head branch' }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :base, class: "form-label" %>
    <%= form.select :base, @branches.map { |branch| [branch['name'], branch['name']] }, { prompt: 'Select base branch' }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control", rows: 4 %>
  </div>

  <%= form.submit "Create Pull Request", class: "btn btn-primary" %>
<% end %>